/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Login (void);
GtkWidget* create_Administator (void);
GtkWidget* create_Add_user (void);
GtkWidget* create_Modify_user_ (void);
GtkWidget* create_Add_election_managment (void);
GtkWidget* create_Modify_election_managment (void);
GtkWidget* create_Electral_list (void);
GtkWidget* create_Add_polling_station (void);
GtkWidget* create_Modify_polling_station (void);
GtkWidget* create_Vote (void);
